{{- $root := . -}}
{{ range $k, $v := .Values.cronjobs }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ regexReplaceAll "_" $k "" | lower }}
  annotations:
    checksum/config: {{ $root.Values.secretsVersion }} # trigger secret redeploy
type: Opaque
stringData:
{{- with $v.secrets }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- with $root.secrets }}
{{- toYaml . | nindent 2 }}
{{- end }}
