apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-log-exporter-config
data:
  config.hcl: |
    listen {
      port = 4040
    }
    namespace "nginx" {
      source = {
        syslog {
          listen_address = "udp://127.0.0.1:8513"
          format = "auto"
          tags = [
            "nginx"
          ]
        }
      }
      format = "$remote_addr - $remote_user [$time_local] \"$request\" rt=$request_time $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
      labels {
        app = "{{ .Values.name }}"
      }
    }
