apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: exporter
      protocol: TCP
      port: 9113
      targetPort: 9113
    - name: log-exporter
      protocol: TCP
      port: 4040
      targetPort: 4040
  selector:
    app: {{ .Values.name }}
